- name: create
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install Python pip module prerequisites (Linux)
      apt:
        name:
          - python3-pip
          - python3-virtualenv
          - python3-setuptools
          - python3-docker
        update_cache: yes
        state: present
      when: ansible_os_family == "Debian"
      become: yes

    - name: Run DataPipeline Docker image
      docker_container:
        name: DataPipeline
        image: pjakovits/radon-ctt-agent:datapipeline
        pull: yes
        ports: 
          - "5000:5000"
        volumes:
          - /mnt:/mnt
      become: yes

