
---
- hosts: all
  vars: 
    get_id1: "processors[0].id" 
      
  tasks:
    
    - name: Get list of available NiFi processors within the process group
      uri:
        url: "http://localhost:{{port}}/nifi-api/process-groups/{{pipeline_id}}/processors"
        method: Get
      register: nifi_resources
      
    - name: Configure the first processor within the process group
      vars:
        first_prcsr_id: "{{ nifi_resources.json  | to_json | from_json | json_query(get_id1) }}"
        
      uri:
        url: "http://localhost:{{port}}/nifi-api/processors/{{first_prcsr_id}}"
        method: PUT
        body:
          "revision": { "version": 0}
          "component": 
            "id": "{{first_prcsr_id}}"
            "config": 
              "properties": { 
                "Mode":"Decrypt",
                "key-derivation-function":"OPENSSL_EVP_BYTES_TO_KEY",
                "Encryption Algorithm":"MD5_128AES",
                "Password":"{{Password}}"
              }
          
                                                          
        status_code: 200
        body_format: json

    




